
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) atof
	@-$(MAKE) cleanall $(CFLAGS) atoi
#	@-$(MAKE) cleanall $(CFLAGS) atol
#	@-$(MAKE) cleanall $(CFLAGS) ecvt
#	@-$(MAKE) cleanall $(CFLAGS) fcvt
#	@-$(MAKE) cleanall $(CFLAGS) gcvt
#	@-$(MAKE) cleanall $(CFLAGS) strtod
	@-$(MAKE) cleanall $(CFLAGS) strtol
#	@-$(MAKE) cleanall $(CFLAGS) strtoul
#	@-$(MAKE) cleanall $(CFLAGS) toascii
#	@-$(MAKE) cleanall $(CFLAGS) tolower
#	@-$(MAKE) cleanall $(CFLAGS) toupper
