
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) alarm_signal
	@-$(MAKE) cleanall $(CFLAGS) kill
	@-$(MAKE) cleanall $(CFLAGS) pause
	@-$(MAKE) cleanall $(CFLAGS) raise_signal
	@-$(MAKE) cleanall $(CFLAGS) sleep
	@-$(MAKE) cleanall $(CFLAGS) usleep

