
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) bzero
	@-$(MAKE) cleanall $(CFLAGS) memcpy
	@-$(MAKE) cleanall $(CFLAGS) memmove
	@-$(MAKE) cleanall $(CFLAGS) memset
	@-$(MAKE) cleanall $(CFLAGS) strcat
	@-$(MAKE) cleanall $(CFLAGS) strchr
	@-$(MAKE) cleanall $(CFLAGS) strcmp
	@-$(MAKE) cleanall $(CFLAGS) strcpy
	@-$(MAKE) cleanall $(CFLAGS) strlen
	@-$(MAKE) cleanall $(CFLAGS) strncat
	@-$(MAKE) cleanall $(CFLAGS) strncmp
	@-$(MAKE) cleanall $(CFLAGS) strncpy
	@-$(MAKE) cleanall $(CFLAGS) strpbrk
	@-$(MAKE) cleanall $(CFLAGS) strrchr
	@-$(MAKE) cleanall $(CFLAGS) strstr
