
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) atexit
	@-$(MAKE) cleanall $(CFLAGS) exit
	@-$(MAKE) cleanall $(CFLAGS) execl_execlp_execle_execv_execvp_execve
	@-$(MAKE) cleanall $(CFLAGS) fork
	@-$(MAKE) cleanall $(CFLAGS) getpid
	@-$(MAKE) cleanall $(CFLAGS) getppid
	@-$(MAKE) cleanall $(CFLAGS) getpriority_setpriority
	@-$(MAKE) cleanall $(CFLAGS) getrusage_getrlimit_setrlimit
	@-$(MAKE) cleanall $(CFLAGS) system
	@-$(MAKE) cleanall $(CFLAGS) vfork
	@-$(MAKE) cleanall $(CFLAGS) wait
	@-$(MAKE) cleanall $(CFLAGS) waitpid
