
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) htonl_htons_ntohl_ntohs
	@-$(MAKE) cleanall $(CFLAGS) inet_addr_aton_ntoa
	@-$(MAKE) cleanall $(CFLAGS) gethostbyaddr
	@-$(MAKE) cleanall $(CFLAGS) gethostbyname
	@-$(MAKE) cleanall $(CFLAGS) getifaddrs_freeifaddrs
	@-$(MAKE) cleanall $(CFLAGS) getservbyname_port_ent_endservent
	@-$(MAKE) cleanall $(CFLAGS) getprotobyname_number_ent_endprotoent
	@-$(MAKE) cleanall $(CFLAGS) getsockopt_setsockopt
	@-$(MAKE) cleanall $(CFLAGS) getaddrinfo
	@-$(MAKE) cleanall $(CFLAGS) getnameinfo
	@-$(MAKE) cleanall $(CFLAGS) inet_ntop_pton
	@-$(MAKE) cleanall $(CFLAGS) gethost_peername
	@-$(MAKE) cleanall $(CFLAGS) TCP_client_writeall_file
	@-$(MAKE) cleanall $(CFLAGS) TCP_read_write
	@-$(MAKE) cleanall $(CFLAGS) TCP_recv_send
	@-$(MAKE) cleanall $(CFLAGS) TCP_server_sendall_file
	@-$(MAKE) cleanall $(CFLAGS) UDP_recvfrom_sendto
	@-$(MAKE) cleanall $(CFLAGS) UDP_recvfrom_sendtoall
	@-$(MAKE) cleanall $(CFLAGS) UDP_recvmsg_sendmsg
