
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) Ch01
	@-$(MAKE) cleanall $(CFLAGS) Ch02
	@-$(MAKE) cleanall $(CFLAGS) Ch03
	@-$(MAKE) cleanall $(CFLAGS) Ch04
	@-$(MAKE) cleanall $(CFLAGS) Ch05
	@-$(MAKE) cleanall $(CFLAGS) Ch06
	@-$(MAKE) cleanall $(CFLAGS) Ch07
#	@-$(MAKE) cleanall $(CFLAGS) Ch08
	@-$(MAKE) cleanall $(CFLAGS) Ch09
#	@-$(MAKE) cleanall $(CFLAGS) Ch10
	@-$(MAKE) cleanall $(CFLAGS) Ch11
	@-$(MAKE) cleanall $(CFLAGS) Ch12
	@-$(MAKE) cleanall $(CFLAGS) Ch13
	@-$(MAKE) cleanall $(CFLAGS) Ch14
	@-$(MAKE) cleanall $(CFLAGS) Ch15
	@-$(MAKE) cleanall $(CFLAGS) Ch16
	@-$(MAKE) cleanall $(CFLAGS) Ch17
	@-$(MAKE) cleanall $(CFLAGS) Ch18
	@-$(MAKE) cleanall $(CFLAGS) Ch19
	@-$(MAKE) cleanall $(CFLAGS) Ch20
	@-$(MAKE) cleanall $(CFLAGS) Ch21
	@-$(MAKE) cleanall $(CFLAGS) Ch22
#	@-$(MAKE) cleanall $(CFLAGS) Ch23
#	@-$(MAKE) cleanall $(CFLAGS) Ch24
	@-$(MAKE) cleanall $(CFLAGS) Ch25
