
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) access
	@-$(MAKE) cleanall $(CFLAGS) chmod
	@-$(MAKE) cleanall $(CFLAGS) chown
	@-$(MAKE) cleanall $(CFLAGS) fstat
	@-$(MAKE) cleanall $(CFLAGS) link
	@-$(MAKE) cleanall $(CFLAGS) lstat
	@-$(MAKE) cleanall $(CFLAGS) mkdir_rmdir
	@-$(MAKE) cleanall $(CFLAGS) opendir_readdir_telldir_seekdir_rewinddir_closedir
	@-$(MAKE) cleanall $(CFLAGS) remove
	@-$(MAKE) cleanall $(CFLAGS) rename
	@-$(MAKE) cleanall $(CFLAGS) stat
	@-$(MAKE) cleanall $(CFLAGS) symlink
	@-$(MAKE) cleanall $(CFLAGS) unlink
