
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) dup
	@-$(MAKE) cleanall $(CFLAGS) dup2
	@-$(MAKE) cleanall $(CFLAGS) close_open_read_write
	@-$(MAKE) cleanall $(CFLAGS) mkstemp
