
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) fdopen
	@-$(MAKE) cleanall $(CFLAGS) feof
	@-$(MAKE) cleanall $(CFLAGS) fgets_fputs
	@-$(MAKE) cleanall $(CFLAGS) fileno
	@-$(MAKE) cleanall $(CFLAGS) fopen_fclose_getc_putc
	@-$(MAKE) cleanall $(CFLAGS) fread_fwrite
	@-$(MAKE) cleanall $(CFLAGS) freopen
	@-$(MAKE) cleanall $(CFLAGS) fseek_ftell
	@-$(MAKE) cleanall $(CFLAGS) getchar_putchar
	@-$(MAKE) cleanall $(CFLAGS) gets_puts_rewind
	@-$(MAKE) cleanall $(CFLAGS) mktemp
	@-$(MAKE) cleanall $(CFLAGS) tmpfile
	