
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
#	@-$(MAKE) cleanall $(CFLAGS) asctime
	@-$(MAKE) cleanall $(CFLAGS) clock
	@-$(MAKE) cleanall $(CFLAGS) ctime
	@-$(MAKE) cleanall $(CFLAGS) difftime
#	@-$(MAKE) cleanall $(CFLAGS) ftime
	@-$(MAKE) cleanall $(CFLAGS) gettimeofday
	@-$(MAKE) cleanall $(CFLAGS) gmtime
	@-$(MAKE) cleanall $(CFLAGS) localtime
	@-$(MAKE) cleanall $(CFLAGS) mktime
#	@-$(MAKE) cleanall $(CFLAGS) settimeofday
	@-$(MAKE) cleanall $(CFLAGS) strftime_strptime
	@-$(MAKE) cleanall $(CFLAGS) time
#	@-$(MAKE) cleanall $(CFLAGS) tzset
