
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) geteuid_seteuid_getegid_setegid
	@-$(MAKE) cleanall $(CFLAGS) getlogin_gethostname_uname_gethostid
	@-$(MAKE) cleanall $(CFLAGS) getpwent_setpwent_endpwent
	@-$(MAKE) cleanall $(CFLAGS) getpw_getpwnam_getpwuid
	@-$(MAKE) cleanall $(CFLAGS) getuid_setuid_getgid_setgid
	@-$(MAKE) cleanall $(CFLAGS) setreuid_setregid
	