
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) fprintf
	@-$(MAKE) cleanall $(CFLAGS) fscanf
	@-$(MAKE) cleanall $(CFLAGS) printf
	@-$(MAKE) cleanall $(CFLAGS) scanf
	@-$(MAKE) cleanall $(CFLAGS) sprintf
	@-$(MAKE) cleanall $(CFLAGS) sscanf
