
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
#	@-$(MAKE) cleanall $(CFLAGS) mkfifo
	@-$(MAKE) cleanall $(CFLAGS) pclose
	@-$(MAKE) cleanall $(CFLAGS) pipe
	@-$(MAKE) cleanall $(CFLAGS) popen
