
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
#	@-$(MAKE) cleanall $(CFLAGS) ftok
	@-$(MAKE) cleanall $(CFLAGS) msgctl_msgget_msgrcv_msgsnd
	@-$(MAKE) cleanall $(CFLAGS) semctl_semget_semop
	@-$(MAKE) cleanall $(CFLAGS) shmat_shmctl_shmdt_shmget
