#include <iostream>

using namespace std;

int main(void)
{
	cout << "Size of type char is " << sizeof(char) << endl;
	cout << "Size of type short is " << sizeof(short) << endl;
	cout << "Size of type int is " << sizeof(int) << endl;
	cout << "Size of type long is " << sizeof(long) << endl;
	cout << "Size of type float is " << sizeof(float) << endl;
	cout << "Size of type double is " << sizeof(double) << endl;
	cout << "Size of type long double is " << sizeof(long double) << endl;

	return 0;
}
