#include <iostream>

using namespace std;

int main(void)
{
	cout << 10+20          << endl;
	cout << 10-5           << endl;
	cout << 10-20          << endl;
	cout << 10*20          << endl;
	cout << 10/3           << endl;
	cout << 10%3           << endl;
	cout << 10+20/10-5     << endl;
	cout << (10+20)/(10-5) << endl;
	cout << 10+20/(10-5)   << endl;
	cout << (10+20)/10-5   << endl;
	cout << 4*5/3%4+7/3    << endl;

	return 0;
}
