
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) isalnum
	@-$(MAKE) cleanall $(CFLAGS) isalpha
	@-$(MAKE) cleanall $(CFLAGS) isascii
	@-$(MAKE) cleanall $(CFLAGS) isblank
	@-$(MAKE) cleanall $(CFLAGS) iscntrl
	@-$(MAKE) cleanall $(CFLAGS) isdigit
	@-$(MAKE) cleanall $(CFLAGS) isgraph
	@-$(MAKE) cleanall $(CFLAGS) islower
	@-$(MAKE) cleanall $(CFLAGS) isprint
	@-$(MAKE) cleanall $(CFLAGS) isspace
	@-$(MAKE) cleanall $(CFLAGS) ispunct
	@-$(MAKE) cleanall $(CFLAGS) isupper
	@-$(MAKE) cleanall $(CFLAGS) isxdigit

