
MAKE := make
CFLAGS := -C

.PHONY: cleanall
cleanall:
	@-$(MAKE) cleanall $(CFLAGS) getopt
	@-$(MAKE) cleanall $(CFLAGS) getopt_long
	@-$(MAKE) cleanall $(CFLAGS) isatty
#	@-$(MAKE) cleanall $(CFLAGS) pselect
	@-$(MAKE) cleanall $(CFLAGS) select
#	@-$(MAKE) cleanall $(CFLAGS) sendfile
#	@-$(MAKE) cleanall $(CFLAGS) ttyname
